### ISSUE TITLE
Trying to assign custom group:children => group causes errors...

### ISSUE THREAD

**Issue by v1k0d3n** [fabriziopandini/vagrant-compose#6]
I've been stumped on this for hours, and I know that I must be missing something...

When I create an entry like the following:

```
cluster.nodes($master_count, 'master') do |master|
  master.memory = $master_memory
  master.ansible_groups = ['kube-master'], ['k8s-cluster:children => ["kube-master"]']
end
```

It causes errors, like https://gist.github.com/v1k0d3n/40492e77366cbf28cee382c1072dfccc

My goal is to get a useful inventory that looks like the following:

```
[etcd]
kargo-etcd1

[kube-master]
kargo-master1

[kube-node]
kargo-worker1
kargo-worker2

[k8s-cluster:children]
kube-master
kube-node
```

I feel like I'm close...but no luck. Do you have any recommendations or is this the result of a bug? I'm pretty sure I'm creating it incorrectly.

**Comment by fabriziopandini** [comment]
Thanks for the interesting question.
This is not a bug, however the error message should be improved; the good news is that you can address your requirement with what is already there. 

If I got i right you are trying to define a [group of groups](http://docs.ansible.com/ansible/intro_inventory.html#hosts-and-groups) into your inventory file.

You have three options to address this with current release of vagrant-compose:
Tips: To quickly check how the inventory file for your cluster looks like simply add `puts config.cluster.ansible_groups` at the end of your VagrantFile, save and issue `vagrant status`command.

**use all_groups (not recommended, but available out of the box and without any change to your Vagrantfile)**
For example, the following fragment of VagrantFile

``` ruby
 ... 
 config.cluster.compose('kargo') do |cluster|
    cluster.nodes(1, 'master') do |master|
      master.ansible_groups = ['kube-master']
    end
    cluster.nodes(3, 'workers') do |worker|
      worker.ansible_groups = ['kube-node']
    end
  end
  ...
```

will generate following ansible groups into your inventory file

```
[kube-master]
kargo-master1

[kube-node]
kargo-worker1
kargo-worker2
```

and also 

```
[all_groups:children]
kube-master
kube-node
```

IMPORTANT. 
- this feature is not documented yet, but already there in the current release
- you cannot rename all_groups 
- you cannot exclude any ansible group from all_groups.
- I can't provide any guarantee of compatibility in future release.

**"manually" add the group of groups (recommended option)**
config.cluster.compose method sets two variables, config.cluster.nodes and config.cluster.ansible_groups. The second one, is a dictionary, and you can simply add a new item for k8s-cluster:children group of groups before creating nodes.

For example, by adding the following line of code to the above vagrant file immediately after config.cluster.compose('kargo') code block and before the loop that effectively provisions nodes:

``` ruby
config.cluster.ansible_groups['k8s-cluster:children'] = ['kube-master', 'kube-nodes']
```

your inventory file will contain also:

```
[k8s-cluster:children]
kube-master
kube-node
```

Please note that you can use this approach also for setting group variables directly into the inventory file using :vars (see ansible documentation).

**use an additional group of hosts instead of groups of groups (alternative not fully "ansible style")**
For example, by changing the following line of codes in the above Vagrantfile

``` ruby
      master.ansible_groups = ['kube-master']
  ...
      workers.ansible_groups = ['kube-node'']
```

Into

``` ruby
      master.ansible_groups = ['kube-master', 'k8s-cluster:children']
  ...
      workers.ansible_groups = ['kube-node', 'k8s-cluster:children']
```

your inventory file will contain also the following group of hosts:

```
[k8s-cluster:children]
kargo-master1
kargo-worker1
kargo-worker2
```

Please let me know if one of the above solutions address your issue; afterwards I will figure out if/how to improve error management and probably also documentation.

**Comment by v1k0d3n** [comment]
this is great information! i cant thank you enough for the added direction. it was just what i needed.

i was still having issues, so i dug in a little deeper. i realized i was using a development branch version of ansible (2.2.0), and that was causing some general strangeness with this plugin. once i reverted back to 2.1.0, it appeared to work correctly when i used your suggestion (and my personal preference):

```
config.cluster.ansible_groups['k8s-cluster:children'] = ['kube-master', 'kube-nodes']
```

just as a heads up; ansible 2.2.0 only accepts the first member value in the group statement above. so only 'kube-master' was being written to the inventory file as a result. very strange...but, now you are aware of it, and i learned something new! win, win. 👍

**Comment by v1k0d3n** [comment]
btw, you don't happen to know how i can write the 'hostmanager' "real" ip address to the inventory file, rather than the NAT port redirect, do you? that's my next problem...and i have no clue where to go. i know it's not a solution for this repo, but can't find anyone on IRC using these these two (although i want to tell **_everyone_** about them now)!

**Comment by fabriziopandini** [comment]
Thanks for the feedback
I added the recommended solution into documentation for next release.

for sake of clarity I moved copied your last question into issue [#7](https://github.com/fabriziopandini/vagrant-compose/issues/7). Please have a look at it.
